# Generated by Django 2.2.16 on 2022-09-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.IntegerField(
                help_text="Укажите год выпуска произведения",
                verbose_name="Год выпуска",
            ),
        ),
    ]
